### ISSUE TITLE
Doesn't encode nonplanar buffer

### ISSUE THREAD

**Issue by longseespace** [s1ddok/SwiftyCVPixelBuffer#2]
I'm trying to encode `depthMap` retrieved from [ARDepthData](https://developer.apple.com/documentation/arkit/ardepthdata) but it doesn't seem to work.

**Comment by s1ddok** [comment]
hmm, do you have a sample project to look at it?

**Comment by longseespace** [comment]
I'm trying to create a nonplanar buffer but looks like SwiftyCVPixelBuffer doesn't support it. The code below expects the buffer to have `planeCount` > 0, but that works for planar buffer only.
https://github.com/s1ddok/SwiftyCVPixelBuffer/blob/4f2f0deb8cd5274692010e6c2f9a183e0d4f9e69/Sources/SwiftyCVPixelBuffer/CVPixelBuffer%2BCodable.swift#L85

Also, the copy implementation doesn't support nonplanar buffer 

https://github.com/s1ddok/SwiftyCVPixelBuffer/blob/4f2f0deb8cd5274692010e6c2f9a183e0d4f9e69/Sources/SwiftyCVPixelBuffer/CVPixelBuffer%2BUtils.swift#L89-L91
